dist: trusty
sudo: false
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - cppcheck
install:
- python -m pip install --user docutils pygments
script:
- cppcheck --error-exitcode=1 *.c
- make
- export LD_PRELOAD="$PWD/libgetenvy.so"
- GETENVY=1 ls > /dev/null
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
