dist: xenial
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - cppcheck
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- cppcheck --error-exitcode=1 *.c
- make
- make test
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
