name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
        cc:
        - gcc
        - clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: run cppcheck
      if: matrix.cc == 'gcc'
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
        sudo apt-get install cppcheck
        cppcheck --error-exitcode=1 *.c
    - name: check C compiler version
      run: ${{matrix.cc}} --version
    - name: build the library
      run:
        make CC=${{matrix.cc}}
    - name: run tests
      run:
        make test
    - name: run install tests
      run: |
        make install PREFIX=~/.local
        make clean
        make test-installed
      env:
        LD_LIBRARY_PATH: /home/runner/.local/lib
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
